export enum ActionsList {
    // Client Actions
    initialize = "initialize",
    join_lobby = "join_lobby",
    change_param = "change_param",
    ready_lobby = "ready_lobby",
    pick_word = "pick_word",
    pick_powerup = "pick_powerup",
    leave_game = "leave_game",
    // Server Actions
    return_lobby_code = "return_lobby_code",
    lobby_does_not_exist = "lobby_does_not_exist",
    successfully_joined_lobby = "successfully_joined_lobby",
    success = "success",
    error = "error",
    start_game = "start_game",
    player_joined = "player_joined",
    player_left = "player_left",
    update_lobby_settings = "update_lobby_settings",
    word_accepted = "word_accepted",
    word_denied = "word_denied",
    end_turn = "end_turn",
    start_turn = "start_turn",
    powerup_denied = "powerup_denied",
    powerup_activated = "powerup_activated",
    you_died = "you_died",
    you_win = "you_win",
}